inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  NewCops: enable
  DisplayStyleGuide: true
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'

Lint/EmptyBlock:
  Exclude:
    - 'spec/lib/tic_tac_toe/game_spec.rb'
